name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      target:
        description: 'PyPI target'
        required: true
        type: choice
        options:
          - testpypi
          - pypi
        default: testpypi

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  publish-pypi:
    name: Publish to PyPI
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.event_name == 'release' || inputs.target == 'pypi') && 'pypi' || 'testpypi' }}
      url: ${{ (github.event_name == 'release' || inputs.target == 'pypi') && 'https://pypi.org/p/zan/' || 'https://test.pypi.org/p/zan/' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: ${{ (github.event_name == 'release' || inputs.target == 'pypi') && 'https://upload.pypi.org/legacy/' || 'https://test.pypi.org/legacy/' }}
          skip-existing: true
